services:
  backend:
    environment:
      CORS_ORIGIN: http://${VM_IP}
  frontend:
    build:
      args:
        - VITE_API_BASE_URL=http://${VM_IP}:3001

networks:
  observability:
    external: false